# Setup
title: My Personal Wiki
url: https://wiki.tsondt.com
author:
  name: tsondt
  url: https://tsondt.com
ga_id: UA-103691933-3

sass:
  sass_dir: public/css
  style: compressed

exclude:
  - "*.sh"
  - "Dockerfile"
  - "Gemfile*"
  - "LICENSE"
  - "README.md"
  - "CNAME"

gems:
  - jekyll-sitemap
